[tools]
bun = "latest"
node = "latest"
pi = "latest"
python = "latest"
uv = "latest"
"pipx:yt-dlp" = "latest"
"github:can1357/oh-my-pi" = "latest"
"npm:typescript" = "latest"
"npm:@colbymchenry/codegraph" = "latest"

[env]
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }

[settings]
experimental = true

[settings.python]
uv_venv_auto = "source"

[settings.github]
use_git_credentials = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
