[tools]
bun = "latest"
node = "latest"
python = "latest"
uv = "latest"
"pipx:yt-dlp" = "latest"
"github:can1357/oh-my-pi" = "latest"
"npm:typescript" = "latest"
"npm:@colbymchenry/codegraph" = "latest"
usage = "latest"
java = "21"

[env]
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }

[settings]
experimental = true
minimum_release_age_excludes = ["github:can1357/oh-my-pi","pi"]

[settings.python]
uv_venv_auto = "source"

[settings.github]
use_git_credentials = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
