frame = "transparent"
mouse-cursor-icon = "arrow"
title-hidden = false
srgb = true
# system-native-tabs = true
# system-pinned-hotkey = "cmd+ctrl+z" # macOS only
# system-switcher-hotkey = "cmd+ctrl+n" # macOS only, requires system-native-tabs = true
# system-tab-prev-hotkey = "cmd+shift+[" # macOS only
# system-tab-next-hotkey = "cmd+shift+]" # macOS only

[font]
normal = [
  "JetBrainsMono Nerd Font",
] # Will use the bundled Fira Code Nerd Font by default
size = 18.0

[box-drawing]
# "font-glyph", "native" or "selected-native"
# mode = "font-glyph"
#
# [box-drawing.sizes]
# default = [2, 4]  # Thin and thick values respectively, for all sizes
#
