# [global]
# overload_tap_timeout = 100

[ids]
*

[main]
tab = overload(nav, tab)
altgr = overload(hyper, rightalt)
capslock = overload(control, capslock)

[nav]
h = left
j = down
k = up
l = right

[hyper:C-M-A-S]
