tap "anomalyco/tap"
tap "nikitabobko/tap"
tap "oven-sh/bun"
tap "surge-downloader/tap"
tap "tinypkg/tap"
brew "agg"
brew "asciinema"
brew "bat"
brew "chezmoi"
brew "cmatrix"
brew "exiftool"
brew "eza"
brew "fd"
brew "ffmpeg-full", link: true
brew "figlet"
brew "fx"
brew "fzf"
brew "genact"
brew "gh"
brew "ghostscript"
brew "git-delta"
brew "gitlogue"
brew "gittype"
brew "htop"
brew "imagemagick-full", link: true
brew "jc"
brew "jq"
brew "lazygit"
brew "lazyssh"
brew "lnav"
brew "lolcat"
brew "mas"
brew "mcat"
brew "mole"
brew "neovim"
brew "node"
brew "poppler"
brew "resvg"
brew "ripgrep"
brew "sevenzip"
brew "starship"
brew "uv"
brew "wget"
brew "yazi"
brew "yq"
brew "zellij"
brew "zoxide"
brew "zsh-vi-mode"
brew "anomalyco/tap/opencode"
brew "oven-sh/bun/bun"
brew "tinypkg/tap/rime-wanxiang-updater"
cask "nikitabobko/tap/aerospace"
cask "browseros"
cask "bruno"
cask "font-jetbrains-mono-nerd-font"
cask "font-lxgw-wenkai"
cask "font-symbols-only-nerd-font"
cask "google-chrome"
cask "karabiner-elements"
cask "lunar"
cask "neovide-app"
cask "obsidian"
cask "qlmarkdown"
cask "surge-downloader/tap/surge"
cask "syntax-highlight"
mas "MacFamilyTree 11", id: 6480510488
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "NetEaseMusic", id: 944848654
mas "Presentify", id: 1507246666
mas "ShellBean", id: 1504613231
mas "SnippetsLab", id: 1006087419
mas "Snippety", id: 1530751461
mas "Step Two", id: 1448916662
mas "TencentMeeting", id: 1484048379
mas "WeChat", id: 836500024
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
