# https://starship.rs/zh-CN/config/
#
"$schema" = "https://starship.rs/config-schema.json"
continuation_prompt = '[▶▶ ](dimmed bright-black)'

[sudo]
disabled = false
symbol = '👩‍💻 '

[shlvl]
disabled = false
format = '[$symbol]($style)'
#symbol = '󱞩 '
symbol = '󱏒 '

repeat = true
repeat_offset = 1

[status]
format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
